version: "3"

services:
  ingest:
    image: codeepblue/go2live-ingest:latest
    ports:
      - "1935:1935"
    links:
      - bridge
    volumes:
      - ./record:/record

  bridge:
    image: codeepblue/go2live-ingest-bridge:latest
    links:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest

  cdn:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx-cdn.conf:/etc/nginx/nginx.conf:ro
      - ./record:/usr/share/nginx/html:ro

  web:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./record:/record
    links:
      - db
      - redis

  db:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=web
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=testing